# Generated by Django 4.2.2 on 2023-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_added_missing_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personparticipant',
            name='nickname_unregistered_participant',
            field=models.CharField(default='defaultMakemigrations', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(default='defaultMakemigrations', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
