# Generated by Django 4.2.2 on 2023-07-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_add_intermediate_without_through_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='personparticipant',
            name='menu_items',
            field=models.ManyToManyField(related_name='participants', through='viewer.PersonParticipantMenuItem', to='viewer.menuitem'),
        ),
    ]
