# Generated by Django 4.2.2 on 2023-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_validators_pers_par_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personparticipant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
