# Generated by Django 4.2.2 on 2023-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_pers_part_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personparticipant',
            name='nickname_unregistered_participant',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
